require:
# rubocop-minitest

AllCops:
  Include:
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/*.rb"
    - "**/*.ru"
    - "**/Rakefile"
    - "**/*.rake"
    - "**/*.jb"
  Exclude:
    - "bin/*"
Documentation:
  Enabled: false
Layout/LineLength:
  Max: 140
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 7
Metrics/ClassLength:
  Max: 210
Metrics/ModuleLength:
  Max: 200
Style/TrivialAccessors:
  Enabled: true
Style/MixinUsage:
  Enabled: true
Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only
Naming/PredicateName:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
    Enabled: true
Lint/RaiseException:
    Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
   Enabled: true
Style/HashTransformKeys:
   Enabled: true
Style/HashTransformValues:
   Enabled: true
Naming/VariableNumber:
  Enabled: false
