# frozen_string_literal: true

require 'czech_post_b2b_client/response_parsers/base_parser'
require 'czech_post_b2b_client/response_parsers/get_stats_parser'
require 'czech_post_b2b_client/response_parsers/get_parcels_printing_parser'
require 'czech_post_b2b_client/response_parsers/get_parcel_state_parser'
require 'czech_post_b2b_client/response_parsers/get_result_parcels_parser'
require 'czech_post_b2b_client/response_parsers/send_parcels_parser'
